name: jeremyhahn
favicon: null
layout_spectrum: 0.15004097460769117
typography_spectrum: 0.4860864800866693
title: My Homepage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff8e6'
    - '#000000'
    - '#828c96'
    - '#00a1fb'
    - '#fe0000'
  brandStrength: 0.13552336604334414
  lightness: 0.43863499513827264
  saturation: 0.5208592035342008
  rhythmicContrast: 0.2042014873586595
purpose: []
